### ISSUE TITLE
“KeyError: 'MaskHungarianAssigner is already registered in bbox_assigner'”

### ISSUE THREAD

**Issue by rockywind** [zhangyp15/OccFormer#2]
Hi, 
Thank you for sharing the great work!
When I run the scipt `bash tools/dist_test.sh projects/configs/occformer_nusc/occformer_nusc_r50_256x704.py /rockywin.wang/occ_net/OccFormer/occformer_nusc_r50.pth 4 --pred-save /rockywin.wang/occ_net/OccFormer/01_pred_dir`
I met the error below.
The version of MMCV is `1.4.0`.
````
te/attempt_3/0/error.json
Traceback (most recent call last):
  File "tools/test.py", line 19, in <module>
    from projects.mmdet3d_plugin.datasets.builder import build_dataloader
  File "/rockywin.wang/occ_net/OccFormer/projects/mmdet3d_plugin/__init__.py", line 1, in <module>
    from .occformer import *
  File "/rockywin.wang/occ_net/OccFormer/projects/mmdet3d_plugin/occformer/__init__.py", line 5, in <module>
    from .mask2former import *
  File "/rockywin.wang/occ_net/OccFormer/projects/mmdet3d_plugin/occformer/mask2former/__init__.py", line 2, in <module>
    from .assigners import *
  File "/rockywin.wang/occ_net/OccFormer/projects/mmdet3d_plugin/occformer/mask2former/assigners/__init__.py", line 1, in <module>
    from .mask_hungarian_assigner import MaskHungarianAssigner
  File "/rockywin.wang/occ_net/OccFormer/projects/mmdet3d_plugin/occformer/mask2former/assigners/mask_hungarian_assigner.py", line 12, in <module>
    class MaskHungarianAssigner(BaseAssigner):
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 312, in _register
    module_class=cls, module_name=name, force=force)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 246, in _register_module
    raise KeyError(f'{name} is already registered '
KeyError: 'MaskHungarianAssigner is already registered in bbox_assigner'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 172562) of binary: /opt/conda/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
````

**Comment by p1tohu1** [comment]
register_module(force=True)
